# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{slow}
  s.version = "1.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Kyle Maxwell"]
  s.date = %q{2011-04-11}
  s.default_executable = %q{slow}
  s.description = %q{A TCP reverse proxy that responds slowly}
  s.email = %q{kmaxwell@twitter.com}
  s.executables = ["slow"]
  s.extra_rdoc_files = [
    "LICENSE",
     "README"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE",
     "README",
     "Rakefile",
     "VERSION",
     "bin/slow",
     "slow.gemspec",
     "test/helper.rb",
     "test/test_slow.rb"
  ]
  s.homepage = %q{http://github.com/fizx/slow}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.6}
  s.summary = %q{A TCP reverse proxy that responds slowly}
  s.test_files = [
    "test/helper.rb",
     "test/test_slow.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<em-proxy>, [">= 0.1.5"])
      s.add_development_dependency(%q<thoughtbot-shoulda>, [">= 0"])
    else
      s.add_dependency(%q<em-proxy>, [">= 0.1.5"])
      s.add_dependency(%q<thoughtbot-shoulda>, [">= 0"])
    end
  else
    s.add_dependency(%q<em-proxy>, [">= 0.1.5"])
    s.add_dependency(%q<thoughtbot-shoulda>, [">= 0"])
  end
end

